const layout1 = [
    [
      { status: 'D', number: 1 },
      null,
      { status: 'D', number: 2 },
      { status: 'D', number: 3 },
      null,
      { status: 'D', number: 4 },
      null,
      { status: 'D', number: 5 },
      { status: 'D', number: 6 },
      null,
      { status: 'D', number: 7 },
    ],
    [
      { status: 'D', number: 8 },
      null,
      { status: 'D', number: 9 },
      { status: 'D', number: 10 },
      null,
      { status: 'D', number: 11 },
      null,
      { status: 'D', number: 12 },
      { status: 'D', number: 13 },
      null,
      { status: 'D', number: 14 },
    ],
    [
      { status: 'D', number: 15 },
      null,
      { status: 'D', number: 16 },
      { status: 'D', number: 17 },
      null,
      null,
      null,
      { status: 'D', number: 18 },
      { status: 'D', number: 19 },
      null,
      { status: 'D', number: 20 },
    ],
    [
      { status: 'D', number: 21 },
      null,
      { status: 'D', number: 22 },
      { status: 'D', number: 23 },
      null,
      { status: 'D', number: 24 },
      null,
      { status: 'D', number: 25 },
      { status: 'D', number: 26 },
      null,
      { status: 'D', number: 27 },
    ],
    [
      { status: 'D', number: 28 },
      null,
      { status: 'D', number: 29 },
      { status: 'D', number: 30 },
      null,
      { status: 'D', number: 31 },
      null,
      { status: 'D', number: 32 },
      { status: 'D', number: 33 },
      null,
      { status: 'D', number: 34 },
    ],
    [
      { status: 'D', number: 35 },
      null,
      { status: 'D', number: 36 },
      { status: 'D', number: 37 },
      null,
      { status: 'D', number: 38 },
      null,
      { status: 'D', number: 39 },
      { status: 'D', number: 40 },
      null,
      { status: 'D', number: 41 },
    ],
    [
      null,
      null,
      { status: 'D', number: 42 },
      { status: 'D', number: 43 },
      null,
      { status: 'D', number: 44 },
      null,
      { status: 'D', number: 45 },
      { status: 'D', number: 46 },
      null,
      { status: 'D', number: 47 },
    ],
    [
      { status: 'D', number: 48 },
      null,
      { status: 'D', number: 49 },
      { status: 'D', number: 50 },
      null,
      { status: 'D', number: 51 },
      null,
      { status: 'D', number: 52 },
      { status: 'D', number: 53 },
      null,
      { status: 'D', number: 54 },
    ],
    [
      { status: 'D', number: 55 },
      null,
      { status: 'D', number: 56 },
      { status: 'D', number: 57 },
      null,
      { status: 'D', number: 58 },
      null,
      { status: 'D', number: 59 },
      { status: 'D', number: 60 },
      null,
      { status: 'D', number: 61 },
    ],
    [
      { status: 'D', number: 62 },
      null,
      { status: 'D', number: 63 },
      { status: 'D', number: 64 },
      null,
      { status: 'D', number: 65 },
      null,
      { status: 'D', number: 66 },
      { status: 'D', number: 67 },
      null,
      { status: 'D', number: 68 },
    ],
    [
      { status: 'D', number: 69 },
      null,
      { status: 'D', number: 70 },
      { status: 'D', number: 71 },
      null,
      { status: 'D', number: 72 },
      null,
      { status: 'D', number: 73 },
      { status: 'D', number: 74 },
      null,
      { status: 'D', number: 75 },
    ],
    [
      { status: 'D', number: 76 },
      null,
      { status: 'D', number: 77 },
      { status: 'D', number: 78 },
      null,
      { status: 'D', number: 79 },
      null,
      { status: 'D', number: 80 },
      { status: 'D', number: 81 },
      null,
      { status: 'D', number: 82 },
    ],
    [
      { status: 'D', number: 83 },
      null,
      { status: 'D', number: 84 },
      { status: 'D', number: 85 },
      null,
      { status: 'D', number: 86 },
      null,
      { status: 'D', number: 87 },
      { status: 'D', number: 88 },
      null,
      { status: 'D', number: 89 },
    ],
    [
      { status: 'D', number: 90 },
      null,
      { status: 'D', number: 91 },
      { status: 'D', number: 92 },
      null,
      { status: 'D', number: 93 },
      null,
      { status: 'D', number: 94 },
      { status: 'D', number: 95 },
      null,
      { status: 'D', number: 96 },
    ],
  ];
  
  const layout2 = [
    [
      { status: 'D', number: 1 },
      null,
      { status: 'D', number: 2 },
      null,
      { status: 'D', number: 3 },
      null,
      { status: 'D', number: 4 },
      null,
      { status: 'D', number: 5 },
    ],
    [
      { status: 'D', number: 6 },
      null,
      { status: 'D', number: 7 },
      null,
      { status: 'D', number: 8 },
      null,
      { status: 'D', number: 9 },
      null,
      { status: 'D', number: 10 },
    ],
    [
      { status: 'D', number: 11 },
      null,
      { status: 'D', number: 12 },
      null,
      { status: 'D', number: 13 },
      null,
      { status: 'D', number: 14 },
      null,
      { status: 'D', number: 15 },
    ],
    [
      { status: 'D', number: 16 },
      null,
      { status: 'D', number: 17 },
      null,
      { status: 'D', number: 18 },
      null,
      { status: 'D', number: 19 },
      null,
      { status: 'D', number: 20 },
    ],
    [
      { status: 'D', number: 21 },
      null,
      { status: 'D', number: 22 },
      null,
      { status: 'D', number: 23 },
      null,
      { status: 'D', number: 24 },
      null,
      { status: 'D', number: 25 },
    ],
    [
      { status: 'D', number: 26 },
      null,
      { status: 'D', number: 27 },
      null,
      { status: 'D', number: 28 },
      null,
      { status: 'D', number: 29 },
      null,
      { status: 'D', number: 30 },
    ],
    [
      { status: 'D', number: 31 },
      null,
      { status: 'D', number: 32 },
      null,
      null,
      null,
      { status: 'D', number: 33 },
      null,
      { status: 'D', number: 34 },
    ],
    [
      { status: 'D', number: 35 },
      null,
      { status: 'D', number: 37 },
      null,
      { status: 'D', number: 36 },
      null,
      { status: 'D', number: 38 },
      null,
      { status: 'D', number: 39 },
    ],
    [
      { status: 'D', number: 40 },
      null,
      { status: 'D', number: 41 },
      null,
      { status: 'D', number: 42 },
      null,
      { status: 'D', number: 43 },
      null,
      { status: 'D', number: 44 },
    ],
    [
      { status: 'D', number: 45 },
      null,
      { status: 'D', number: 46 },
      null,
      { status: 'D', number: 47 },
      null,
      { status: 'D', number: 48 },
      null,
      { status: 'D', number: 49 },
    ],
    [
      { status: 'D', number: 50 },
      null,
      { status: 'D', number: 51 },
      null,
      { status: 'D', number: 52 },
      null,
      { status: 'D', number: 53 },
      null,
      { status: 'D', number: 54 },
    ],
    [
      { status: 'D', number: 55 },
      null,
      { status: 'D', number: 56 },
      null,
      { status: 'D', number: 57 },
      null,
      { status: 'D', number: 58 },
      null,
      { status: 'D', number: 59 },
    ],
    [
      { status: 'D', number: 60 },
      null,
      { status: 'D', number: 61 },
      null,
      { status: 'D', number: 62 },
      null,
      { status: 'D', number: 63 },
      null,
      { status: 'D', number: 64 },
    ],
    [
      { status: 'D', number: 65 },
      null,
      { status: 'D', number: 66 },
      null,
      { status: 'D', number: 67 },
      null,
      { status: 'D', number: 68 },
      null,
      { status: 'D', number: 69 },
    ],
  ];
  
  const layout3 = [
    [
      { status: 'D', number: 1 },
      { status: 'D', number: 2 },
      null,
      { status: 'D', number: 3 },
      { status: 'D', number: 4 },
      null,
      { status: 'D', number: 5 },
      { status: 'D', number: 6 },
      null,
      { status: 'D', number: 7 },
      { status: 'D', number: 8 },
      null,
      { status: 'D', number: 9 },
      { status: 'D', number: 10 },
    ],
    [
      { status: 'D', number: 11 },
      { status: 'D', number: 12 },
      null,
      { status: 'D', number: 13 },
      { status: 'D', number: 14 },
      null,
      { status: 'D', number: 15 },
      { status: 'D', number: 16 },
      null,
      { status: 'D', number: 17 },
      { status: 'D', number: 18 },
      null,
      { status: 'D', number: 19 },
      { status: 'D', number: 20 },
    ],
    [
      { status: 'D', number: 21 },
      { status: 'D', number: 22 },
      null,
      { status: 'D', number: 23 },
      { status: 'D', number: 24 },
      null,
      null,
      null,
      null,
      { status: 'D', number: 25 },
      { status: 'D', number: 26 },
      null,
      { status: 'D', number: 27 },
      { status: 'D', number: 28 },
    ],
    [
      { status: 'D', number: 29 },
      { status: 'D', number: 30 },
      null,
      { status: 'D', number: 31 },
      { status: 'D', number: 32 },
      null,
      { status: 'D', number: 33 },
      { status: 'D', number: 34 },
      null,
      { status: 'D', number: 35 },
      { status: 'D', number: 36 },
      null,
      { status: 'D', number: 37 },
      { status: 'D', number: 38 },
    ],
    [
      { status: 'D', number: 39 },
      { status: 'D', number: 40 },
      null,
      { status: 'D', number: 41 },
      { status: 'D', number: 42 },
      null,
      { status: 'D', number: 43 },
      { status: 'D', number: 44 },
      null,
      { status: 'D', number: 45 },
      { status: 'D', number: 46 },
      null,
      { status: 'D', number: 47 },
      { status: 'D', number: 48 },
    ],
    [
      { status: 'D', number: 49 },
      { status: 'D', number: 50 },
      null,
      { status: 'D', number: 51 },
      { status: 'D', number: 52 },
      null,
      { status: 'D', number: 53 },
      { status: 'D', number: 54 },
      null,
      { status: 'D', number: 55 },
      { status: 'D', number: 56 },
      null,
      { status: 'D', number: 57 },
      { status: 'D', number: 58 },
    ],
    [
      null,
      null,
      null,
      { status: 'D', number: 59 },
      { status: 'D', number: 60 },
      null,
      { status: 'D', number: 61 },
      { status: 'D', number: 62 },
      null,
      { status: 'D', number: 63 },
      { status: 'D', number: 64 },
      null,
      { status: 'D', number: 65 },
      { status: 'D', number: 66 },
    ],
    [
      { status: 'D', number: 67 },
      { status: 'D', number: 68 },
      null,
      { status: 'D', number: 69 },
      { status: 'D', number: 70 },
      null,
      { status: 'D', number: 71 },
      { status: 'D', number: 72 },
      null,
      { status: 'D', number: 73 },
      { status: 'D', number: 74 },
      null,
      { status: 'D', number: 75 },
      { status: 'D', number: 76 },
    ],
    [
      { status: 'D', number: 77 },
      { status: 'D', number: 78 },
      null,
      { status: 'D', number: 79 },
      { status: 'D', number: 80 },
      null,
      { status: 'D', number: 81 },
      { status: 'D', number: 82 },
      null,
      { status: 'D', number: 83 },
      { status: 'D', number: 84 },
      null,
      { status: 'D', number: 85 },
      { status: 'D', number: 86 },
    ],
    [
      { status: 'D', number: 87 },
      { status: 'D', number: 88 },
      null,
      { status: 'D', number: 89 },
      { status: 'D', number: 90 },
      null,
      { status: 'D', number: 91 },
      { status: 'D', number: 92 },
      null,
      { status: 'D', number: 93 },
      { status: 'D', number: 94 },
      null,
      { status: 'D', number: 95 },
      { status: 'D', number: 96 },
    ],
    [
      { status: 'D', number: 97 },
      { status: 'D', number: 98 },
      null,
      { status: 'D', number: 99 },
      { status: 'D', number: 100 },
      null,
      { status: 'D', number: 101 },
      { status: 'D', number: 102 },
      null,
      { status: 'D', number: 103 },
      { status: 'D', number: 104 },
      null,
      { status: 'D', number: 105 },
      { status: 'D', number: 106 },
    ],
    [
      { status: 'D', number: 107 },
      { status: 'D', number: 108 },
      null,
      { status: 'D', number: 109 },
      { status: 'D', number: 110 },
      null,
      { status: 'D', number: 111 },
      { status: 'D', number: 112 },
      null,
      { status: 'D', number: 113 },
      { status: 'D', number: 114 },
      null,
      { status: 'D', number: 115 },
      { status: 'D', number: 116 },
    ],
    [
      { status: 'D', number: 117 },
      { status: 'D', number: 118 },
      null,
      { status: 'D', number: 119 },
      { status: 'D', number: 120 },
      null,
      { status: 'D', number: 121 },
      { status: 'D', number: 122 },
      null,
      { status: 'D', number: 123 },
      { status: 'D', number: 124 },
      null,
      { status: 'D', number: 125 },
      { status: 'D', number: 126 },
    ],
    [
      { status: 'D', number: 127 },
      { status: 'D', number: 128 },
      null,
      { status: 'D', number: 129 },
      { status: 'D', number: 130 },
      null,
      { status: 'D', number: 131 },
      { status: 'D', number: 132 },
      null,
      { status: 'D', number: 133 },
      { status: 'D', number: 134 },
      null,
      { status: 'D', number: 135 },
      { status: 'D', number: 136 },
    ],
  ];
  
  const layout4 = [
    [
      { status: 'D', number: 1 },
      { status: 'D', number: 2 },
      null,
      { status: 'D', number: 3 },
      { status: 'D', number: 4 },
      { status: 'D', number: 5 },
      null,
      { status: 'D', number: 6 },
      { status: 'D', number: 7 },
      { status: 'D', number: 8 },
      null,
      { status: 'D', number: 9 },
      { status: 'D', number: 10 },
      { status: 'D', number: 11 },
      null,
      { status: 'D', number: 12 },
      { status: 'D', number: 13 },
    ],
    [
      { status: 'D', number: 14 },
      { status: 'D', number: 15 },
      null,
      { status: 'D', number: 16 },
      { status: 'D', number: 17 },
      { status: 'D', number: 18 },
      null,
      { status: 'D', number: 19 },
      { status: 'D', number: 20 },
      { status: 'D', number: 21 },
      null,
      { status: 'D', number: 22 },
      { status: 'D', number: 23 },
      { status: 'D', number: 24 },
      null,
      { status: 'D', number: 25 },
      { status: 'D', number: 26 },
    ],
    [
      { status: 'D', number: 27 },
      { status: 'D', number: 28 },
      null,
      { status: 'D', number: 29 },
      { status: 'D', number: 30 },
      { status: 'D', number: 31 },
      null,
      null,
      null,
      null,
      null,
      { status: 'D', number: 32 },
      { status: 'D', number: 33 },
      { status: 'D', number: 34 },
      null,
      { status: 'D', number: 35 },
      { status: 'D', number: 36 },
    ],//
    [
      { status: 'D', number: 37 },
      { status: 'D', number: 38 },
      null,
      { status: 'D', number: 39 },
      { status: 'D', number: 40 },
      { status: 'D', number: 41 },
      null,
      { status: 'D', number: 42 },
      { status: 'D', number: 43 },
      { status: 'D', number: 44 },
      null,
      { status: 'D', number: 45 },
      { status: 'D', number: 46 },
      { status: 'D', number: 47 },
      null,
      { status: 'D', number: 48 },
      { status: 'D', number: 49 },
    ],
    [
      { status: 'D', number: 50 },
      { status: 'D', number: 51 },
      null,
      { status: 'D', number: 52 },
      { status: 'D', number: 53 },
      { status: 'D', number: 54 },
      null,
      { status: 'D', number: 55 },
      { status: 'D', number: 56 },
      { status: 'D', number: 57 },
      null,
      { status: 'D', number: 58 },
      { status: 'D', number: 59 },
      { status: 'D', number: 60 },
      null,
      { status: 'D', number: 61 },
      { status: 'D', number: 62 },
    ],
    [
      { status: 'D', number: 63 },
      { status: 'D', number: 64 },
      null,
      { status: 'D', number: 65 },
      { status: 'D', number: 66 },
      { status: 'D', number: 67 },
      null,
      { status: 'D', number: 68 },
      { status: 'D', number: 69 },
      { status: 'D', number: 70 },
      null,
      { status: 'D', number: 71 },
      { status: 'D', number: 72 },
      { status: 'D', number: 73 },
      null,
      { status: 'D', number: 74 },
      { status: 'D', number: 75 },
    ],
    [
      null,
      null,
      null,
      { status: 'D', number: 76 },
      { status: 'D', number: 77 },
      { status: 'D', number: 78 },
      null,
      { status: 'D', number: 79 },
      { status: 'D', number: 80 },
      { status: 'D', number: 81 },
      null,
      { status: 'D', number: 82 },
      { status: 'D', number: 83 },
      { status: 'D', number: 84 },
      null,
      { status: 'D', number: 85 },
      { status: 'D', number: 86 },
    ],
    [
      { status: 'D', number: 87 },
      { status: 'D', number: 88 },
      null,
      { status: 'D', number: 89 },
      { status: 'D', number: 90 },
      { status: 'D', number: 91 },
      null,
      { status: 'D', number: 92 },
      { status: 'D', number: 93 },
      { status: 'D', number: 94 },
      null,
      { status: 'D', number: 95 },
      { status: 'D', number: 96 },
      { status: 'D', number: 97 },
      null,
      { status: 'D', number: 98 },
      { status: 'D', number: 99 },
    ],
    [
      { status: 'D', number: 100 },
      { status: 'D', number: 101 },
      null,
      { status: 'D', number: 102 },
      { status: 'D', number: 103 },
      { status: 'D', number: 104 },
      null,
      { status: 'D', number: 105 },
      { status: 'D', number: 106 },
      { status: 'D', number: 107 },
      null,
      { status: 'D', number: 108 },
      { status: 'D', number: 109 },
      { status: 'D', number: 110 },
      null,
      { status: 'D', number: 111 },
      { status: 'D', number: 112 },
    ],
    [
      { status: 'D', number: 113 },
      { status: 'D', number: 114 },
      null,
      { status: 'D', number: 115 },
      { status: 'D', number: 116 },
      { status: 'D', number: 117 },
      null,
      { status: 'D', number: 118 },
      { status: 'D', number: 119 },
      { status: 'D', number: 120 },
      null,
      { status: 'D', number: 121 },
      { status: 'D', number: 122 },
      { status: 'D', number: 123 },
      null,
      { status: 'D', number: 124 },
      { status: 'D', number: 125 },
    ],
    [
      { status: 'D', number: 126 },
      { status: 'D', number: 127 },
      null,
      { status: 'D', number: 128 },
      { status: 'D', number: 129 },
      { status: 'D', number: 130 },
      null,
      { status: 'D', number: 131 },
      { status: 'D', number: 132 },
      { status: 'D', number: 133 },
      null,
      { status: 'D', number: 134 },
      { status: 'D', number: 135 },
      { status: 'D', number: 136 },
      null,
      { status: 'D', number: 137 },
      { status: 'D', number: 138 },
    ], [
      { status: 'D', number: 139 },
      { status: 'D', number: 140 },
      null,
      { status: 'D', number: 141 },
      { status: 'D', number: 142 },
      { status: 'D', number: 143 },
      null,
      { status: 'D', number: 144 },
      { status: 'D', number: 145 },
      { status: 'D', number: 146 },
      null,
      { status: 'D', number: 147 },
      { status: 'D', number: 148 },
      { status: 'D', number: 149 },
      null,
      { status: 'D', number: 150 },
      { status: 'D', number: 151 },
    ],
    [
      { status: 'D', number: 152 },
      { status: 'D', number: 153 },
      null,
      { status: 'D', number: 154 },
      { status: 'D', number: 155 },
      { status: 'D', number: 156 },
      null,
      { status: 'D', number: 157 },
      { status: 'D', number: 158 },
      { status: 'D', number: 159 },
      null,
      { status: 'D', number: 160 },
      { status: 'D', number: 161 },
      { status: 'D', number: 162 },
      null,
      { status: 'D', number: 163 },
      { status: 'D', number: 164 },
    ],
    [
      { status: 'D', number: 165 },
      { status: 'D', number: 166 },
      null,
      { status: 'D', number: 167 },
      { status: 'D', number: 168 },
      { status: 'D', number: 169 },
      null,
      { status: 'D', number: 170 },
      { status: 'D', number: 171 },
      { status: 'D', number: 172 },
      null,
      { status: 'D', number: 173 },
      { status: 'D', number: 174 },
      { status: 'D', number: 175 },
      null,
      { status: 'D', number: 176 },
      { status: 'D', number: 177 },
    ],
  ];

  const layouts = {
    familia: layout4,
    individual: layout2,
  };
  
  export default layouts;
  